export const MAKE_LOGIN = "MAKE_LOGIN"
export const MAKE_SIGNUP = "MAKE_SIGNUP"
export const SORT_DATA = "SORT_DATA"
export const ITEM_DATA = "ITEM_DATA"
export const COUNT_DATA = "COUNT_DATA"
export const RESET_CART = "RESET_CART"